export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'
export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
export const USERS_RESET_FOLLOW_LOAD = 'USERS_RESET_FOLLOW_LOAD'

export const USERS_UNFOLLOWING_POST = 'USERS_UNFOLLOWING_POST'
export const CLEAR_DATA = 'CLEAR_DATA'
